version: '3.2'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    image: iris-aa-server:2020.3AA
    container_name: backend-demo
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - ./backend:/app

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    container_name: frontend-demo
    ports:
    - "4200:4200"

    # usual way to ignore node_modules subfolder
    # volumes:
    #- ./frontend:/app
    #- /app/node_modules
    
    # workaround to Docker issue https://github.com/moby/moby/issues/38564
    volumes:
    - ./frontend/e2e:/app/e2e
    - ./frontend/src:/app/src

  tf2jupyter:   # tensorflow with jupyter 
    build:
      context: ./tf2-jupyter-jdbc
    image: tf2-jupyter-jdbc:1.0.0-iml-template
    hostname: tf2jupyter
    restart: on-failure
    ports:
    - 8896:8888 # 8888 is the docker jupyter service port
    - 6026:6006 # 6006 is the tensorboard port
    volumes:
    - ./jupyter-samples:/tf   #shared volumes